/**
 * Enumeration of possible outcomes from the biometric matching engine.
 */
export enum MatchDecision {
  /** The similarity score met or exceeded the strict match threshold. */
  MATCH = 'MATCH',
  /** The score fell below the match threshold, but remained above the failure cutoff. */
  RETRY = 'RETRY',
  /** The score fell below the cutoff, definitively indicating a different person. */
  FAIL = 'FAIL',
}

/**
 * Configuration parameters for the threshold policy.
 */
export interface ThresholdConfig {
  /** The minimum cosine similarity score required for a MATCH (e.g. 0.80). */
  matchThreshold: number;
  /** The minimum score required to grant a RETRY rather than a hard FAIL (e.g. 0.70). */
  retryThreshold: number;
}

/**
 * Final output generated by the MatchingService for a single comparison.
 */
export interface MatchResult {
  /** The computed cosine similarity score [-1.0, 1.0]. */
  score: number;
  /** The definitive business logic decision. */
  decision: MatchDecision;
  /** A pseudo-probability/confidence score [0, 100] representing certainty of the decision. */
  confidence: number;
  /** Latency of the match calculation in milliseconds. */
  timeMs: number;
}

/**
 * Aggregated performance metrics for the matching subsystem.
 */
export interface MatchingMetrics {
  /** Rolling average time taken for a match comparison (in ms). */
  averageMatchTimeMs: number;
  /** Highest recorded match time in the session (in ms). */
  peakMatchTimeMs: number;
  /** Total number of match comparisons executed in this session. */
  comparisonCount: number;
}
